version: '3.6'
services:

  builder:
    image: josuedlt/webrun-build
    # network_mode: host
    build: 
      context: .
      dockerfile: build.Dockerfile
    # ports:
    #   - 80:80
    volumes:
      - ./build:/build
    #   - ./webrun.config:/webrun.config
    # environment:
    #   - WEBRUN_PORT=80
    #   - WEBRUN_CONFIG=/webrun.config
    #   - WEBRUN_ROUTE_1=/ ls

